#!/usr/bin/env bash
set -euo pipefail

branch="trail-hunk-dev/review-current"
base_branch="main"
worktree_name="review-current"
mode="open"
dry_run=0

usage() {
  cat <<'USAGE'
Usage: scripts/dev-review-current.sh [open|setup|reset] [--dry-run]

Creates or refreshes a real draft GitHub pull request from a snapshot of the
current checkout, then optionally launches trail-hunk from the PR worktree.

Commands:
  open       Create/update the PR worktree and launch trail-hunk. This is the default.
  setup      Create/update the PR worktree and print the launch command.
  reset      Remove the generated review-current worktree and local branch.

Options:
  --dry-run  Print the planned workflow without mutating git or GitHub.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    open|setup|reset)
      mode="$1"
      ;;
    --dry-run)
      dry_run=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'unknown argument: %s\n\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

repo_root="$(git rev-parse --show-toplevel)"
worktree="$repo_root/.dev/worktrees/$worktree_name"
remote_url="$(git -C "$repo_root" config --get remote.origin.url || true)"
source_head="$(git -C "$repo_root" rev-parse --short HEAD)"
source_ref="$(git -C "$repo_root" rev-parse HEAD)"
source_branch="$(git -C "$repo_root" branch --show-current)"
if [[ -z "$source_branch" ]]; then
  source_branch="detached-$source_head"
fi

run() {
  if [[ "$dry_run" -eq 1 ]]; then
    printf '+ %q' "$1"
    shift
    for arg in "$@"; do
      printf ' %q' "$arg"
    done
    printf '\n'
    return 0
  fi
  "$@"
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf 'missing required command: %s\n' "$1" >&2
    exit 1
  fi
}

print_summary() {
  cat <<SUMMARY
trail-hunk review-current workflow
mode: $mode
branch: $branch
base: $base_branch
source: $source_branch@$source_head
worktree: $worktree
remote: ${remote_url:-unknown}
snapshot: tracked diff plus untracked non-ignored files

next:
  cd $worktree
  go run ./cmd/trail-hunk
SUMMARY
}

remove_worktree() {
  if git -C "$repo_root" worktree list --porcelain | grep -Fqx "worktree $worktree"; then
    run git -C "$repo_root" worktree remove --force "$worktree"
  elif [[ -d "$worktree" ]]; then
    run rm -rf "$worktree"
  fi
}

delete_local_branch() {
  if git -C "$repo_root" show-ref --verify --quiet "refs/heads/$branch"; then
    run git -C "$repo_root" branch -D "$branch"
  fi
}

create_worktree() {
  run git -C "$repo_root" fetch origin "$base_branch"
  run git -C "$repo_root" worktree prune
  remove_worktree
  delete_local_branch
  run git -C "$repo_root" worktree add -B "$branch" "$worktree" "$source_ref"
}

apply_tracked_diff() {
  if git -C "$repo_root" diff --quiet HEAD --; then
    return 0
  fi

  if [[ "$dry_run" -eq 1 ]]; then
    run git -C "$repo_root" diff --binary HEAD
    run git -C "$worktree" apply --binary
    return 0
  fi

  git -C "$repo_root" diff --binary HEAD | git -C "$worktree" apply --binary
}

copy_untracked_files() {
  if [[ "$dry_run" -eq 1 ]]; then
    run git -C "$repo_root" ls-files --others --exclude-standard
    run cp "<untracked non-ignored files>" "$worktree"
    return 0
  fi

  while IFS= read -r -d '' path; do
    mkdir -p "$worktree/$(dirname "$path")"
    cp -R "$repo_root/$path" "$worktree/$path"
  done < <(git -C "$repo_root" ls-files --others --exclude-standard -z)
}

commit_snapshot() {
  run git -C "$worktree" add -A
  if [[ "$dry_run" -eq 1 ]]; then
    run git -C "$worktree" commit -m "dev: snapshot current trail-hunk checkout"
    return 0
  fi

  if git -C "$worktree" diff --cached --quiet; then
    printf 'no uncommitted local changes to snapshot; using %s as-is\n' "$source_head"
    return 0
  fi

  run git -C "$worktree" commit -m "dev: snapshot current trail-hunk checkout"
}

push_and_open_pr() {
  run git -C "$worktree" push --force-with-lease -u origin "$branch"

  if [[ "$dry_run" -eq 1 ]]; then
    run gh pr view "$branch"
    run gh pr create --draft --base "$base_branch" --head "$branch" --title "Review current trail-hunk checkout"
    return 0
  fi

  local repo
  repo="$(gh_repo_slug)"
  if gh pr view "$branch" --repo "$repo" >/dev/null 2>&1; then
    printf 'reusing existing draft PR for %s\n' "$branch"
    gh pr view "$branch" --repo "$repo" --json url --jq .url
    return 0
  fi

  gh pr create \
    --draft \
    --base "$base_branch" \
    --head "$branch" \
    --title "Review current trail-hunk checkout" \
    --body "$(pr_body)"
}

gh_repo_slug() {
  local slug
  slug="$(gh repo view --json nameWithOwner --jq .nameWithOwner)"
  printf '%s' "$slug"
}

pr_body() {
  cat <<BODY
This draft PR is generated by \`mise run dev:review-current\`.

It mirrors the local trail-hunk checkout from:

- source branch: $source_branch
- source commit: $source_ref

If the source checkout had uncommitted tracked or untracked non-ignored files,
they were copied into the generated worktree and committed as a temporary dev
snapshot. The source checkout was not modified.
BODY
}

launch_tui() {
  if [[ "$mode" != "open" ]]; then
    return 0
  fi

  if [[ "$dry_run" -eq 1 ]]; then
    run bash -lc "cd '$worktree' && go run ./cmd/trail-hunk"
    return 0
  fi

  cd "$worktree"
  exec go run ./cmd/trail-hunk
}

main() {
  require_command git
  require_command gh

  print_summary
  printf '\n'

  if [[ "$dry_run" -eq 1 ]]; then
    printf 'planned actions:\n'
  fi

  if [[ "$mode" == "reset" ]]; then
    remove_worktree
    delete_local_branch
    printf '\nremoved review-current worktree and local branch\n'
    return 0
  fi

  create_worktree
  apply_tracked_diff
  copy_untracked_files
  commit_snapshot
  push_and_open_pr

  printf '\nready:\n'
  printf '  cd %s\n' "$worktree"
  printf '  go run ./cmd/trail-hunk\n'

  launch_tui
}

main
